on:
  push:
    branches:
      - "main"
jobs:
  check:
    runs-on: "ubuntu-latest-m"
    concurrency:  
      cancel-in-progress: true
      group: "${{ github.event_name }}-${{ github.ref_name }}-${{ github.ref_type }}--${{ github.ref }}-check"
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: composable
          skipPush: false
      - run: nix run .#ci --print-build-logs --verbose

  publish:
    if: github.event_name == 'push'
    runs-on: "ubuntu-latest-m"
    concurrency:  
      cancel-in-progress: true
      group: "main"      
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: composable
          skipPush: false
      - run: nix run .#ci
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          rolling: true      